/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiComposeRouteImport } from './routes/api/ai/compose'
import { Route as ApiAiCoverRouteImport } from './routes/api/ai/cover'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiComposeRoute = ApiAiComposeRouteImport.update({
  id: '/api/ai/compose',
  path: '/api/ai/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCoverRoute = ApiAiCoverRouteImport.update({
  id: '/api/ai/cover',
  path: '/api/ai/cover',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai/compose': typeof ApiAiComposeRoute
  '/api/ai/cover': typeof ApiAiCoverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai/compose': typeof ApiAiComposeRoute
  '/api/ai/cover': typeof ApiAiCoverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai/compose': typeof ApiAiComposeRoute
  '/api/ai/cover': typeof ApiAiCoverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ai/compose' | '/api/ai/cover'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai/compose' | '/api/ai/cover'
  id: '__root__' | '/' | '/api/ai/compose' | '/api/ai/cover'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiComposeRoute: typeof ApiAiComposeRoute
  ApiAiCoverRoute: typeof ApiAiCoverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/compose': {
      id: '/api/ai/compose'
      path: '/api/ai/compose'
      fullPath: '/api/ai/compose'
      preLoaderRoute: typeof ApiAiComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/cover': {
      id: '/api/ai/cover'
      path: '/api/ai/cover'
      fullPath: '/api/ai/cover'
      preLoaderRoute: typeof ApiAiCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiComposeRoute: ApiAiComposeRoute,
  ApiAiCoverRoute: ApiAiCoverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
